### ISSUE TITLE
tutorial: SSD with tensorflow/models 

### ISSUE THREAD

**Issue by peaceiris** [SI-Aizu/documentation#105]
- [tensorflow/models: Models and examples built with TensorFlow](https://github.com/tensorflow/models)

Contents

- Bing Image Search (#113 ) で `cat` の画像を収集
- VoTT でアノテーション (ear, nose)
- SSD で学習

**Comment by peaceiris** [comment]
@missaa000 アノテーション作業もありますか?

VoTT のページはありますが、コンテンツは外部リポジトリに存在します。cf. #65
https://si-aizu.github.io/documentation/Tutorial-VoTT/

**Comment by missaa000** [comment]
Linuxにインストールしているサイトがあまり見つからなかったので助かりました。
ありがとうございます。
アノテーション作業もあるので少し勧めてみます。

**Comment by peaceiris** [comment]
VoTT のドキュメントは[こっち](https://si-aizu.github.io/documentation/Tutorial-VoTT/)に移動しました。

**Comment by peaceiris** [comment]
@missaa000 追加しました。

https://si-aizu.github.io/documentation/Tutorial-TensorFlow-Models

**Comment by peaceiris** [comment]
何か質問があれば新しく issue を立ててください。
