### ISSUE TITLE
環境構築

### ISSUE THREAD

**Issue by NorikoM41** [SI-Aizu/documentation#156]
とりあえずtutorialをしたくて、環境構築をしたら良いのかなって思って
ubuntu?をダウンロードしてる最中なんですけど、あってますか？

すみませんが初歩的なことから教えていただけると嬉しいです

**Comment by peaceiris** [comment]
推論するだけならmacでもできます。

**Comment by peaceiris** [comment]
@Kaito-Aizu Ubuntu 18.04 の DVD ってまだ手元にあるかな?

**Comment by S-Kaisei** [comment]
@peaceiris setup の Documents 見てて思ったけど、ubuntu のインストールする手順を日本語でまとめた方がいいかもね。こっちの研究室で 18 にバージョン上げるためにクリーンインストールする予定あるからまとめよっか？いつになるか分からないけど。

**Comment by peaceiris** [comment]
それは助かる。
この手の情報は `ubuntu インストール` で調べるとたくさん出てくるから、わざわざここで書く必要はないと思ってた。
作るなら「有用な記事を引用してくる」程度の簡単なまとめでいいと思う。

> ついでに必要なパッケージをインストールするシェルスクリプトを書くのもアリかも。

スクリプト書いて楽になりそうな処理がもしあればほしいね。(あまり凝らなくていいと思う。)

**Comment by peaceiris** [comment]
公式サイトのリンク紹介すれば十分かも
[Install Ubuntu desktop | Ubuntu](https://ubuntu.com/tutorials/install-ubuntu-desktop#1-overview)

**Comment by S-Kaisei** [comment]
見てみたけど、確かに公式で十分そうだね。
@NorikoM41 分からないことがあったらなんでも issue で聞いてくださいね。

**Comment by Kaito-Aizu** [comment]
@peaceiris おそらく研究室の僕の机のところにあると思います。

**Comment by peaceiris** [comment]
@Kaito-Aizu 了解です。

@NorikoM41 では、USB で問題がある場合は DVD を試してみてください。

**Comment by NorikoM41** [comment]
@peaceiris @S-Kaisei @Kaito-Aizu さん、ありがとうございます。
暇をみてインストール等進めていきます！
