### ISSUE TITLE
VoTTのexport

### ISSUE THREAD

**Issue by missaa000** [SI-Aizu/documentation#178]
VoTTで画像を囲んでエクスポートしたのですが、出力はjsonファイルとタグ付けした画像のみであっていますか？
出力された画像は囲んだ四角も追加されていると思っていたのですが、ただの画像であっていますか？

**Comment by peaceiris** [comment]
https://si-aizu.github.io/documentation/Tutorial-TensorFlow-Models/ の SSD とかを使いたいのであれば、https://si-aizu.github.io/documentation/Tutorial-VoTT/#export_dataset に従って tfrecord 形式 (jsonファイルとタグ付けした画像が一つになったもの) で出力します。この場合 jsonファイルとタグ付けした画像は不要ですが、後から使いたいこともあるかもしれないので、とっておくことをオススメします。
