### ISSUE TITLE
deps: bump tensorflow-gpu from 2.2.0 to 2.3.0

### ISSUE THREAD

**Issue by peaceiris** [SI-Aizu/documentation#250]
- [deps: bump tensorflow-gpu from 2.2.0 to 2.3.0 in /docs/Tutorial-TensorFlow by dependabot · Pull Request #247 · SI-Aizu/documentation](https://github.com/SI-Aizu/documentation/pull/247)

```
python3 -m pip list -o
python3 -m pip install -U pkg_name
```

で他の依存と同時に更新する必要がある。なので local でしかできない作業。(#247 で dependabot にお任せはできない。)

## Breaking Changes 破壊的変更

- [Release TensorFlow 2.3.0 · tensorflow/tensorflow](https://github.com/tensorflow/tensorflow/releases/tag/v2.3.0)

`tf.data` まわりを入念に確認した方がいいかも。

**Comment by peaceiris** [comment]
[Release TensorFlow Official Models 2.3.0 · tensorflow/models](https://github.com/tensorflow/models/releases/tag/v2.3.0)

**Comment by S-Kaisei** [comment]
- [x] K_fold_cross_validation.py
- [x] augmentation.py
- [x] cifar10.py
- [x] mnist.py

**Comment by peaceiris** [comment]
https://github.com/SI-Aizu/documentation/pull/269#issuecomment-667806092

TensorFlow Upgrade 手順

以下のファイルのタグを更新

- Dockerfile
- docker-compose.yml
- Makefile

`requirements.txt` を空にして

```
docker-compose build
make run
```

```
python -m pip install matplotlib seaborn pandas opencv-python sklearn jupyterlab scipy
python -m pip freeze > requirements.txt
```

```
docker-compose build
```
