### ISSUE TITLE
setup: Ubuntu 18.04, GPU, NVIDIA container toolkit

### ISSUE THREAD

**Issue by peaceiris** [SI-Aizu/documentation#32]
- [Ubuntu 18.04 GeForce RTX 2080 GPU Deep Learning - Qiita](https://qiita.com/peaceiris/items/21fb40964c875b91439f)

## Contents

- Ubuntu Boot USB の作り方
- GPU のセットアップ方法
- Docker から GPU を使えるようにする設定

**Comment by peaceiris** [comment]
@S-Kaisei この[記事](https://qiita.com/peaceiris/items/21fb40964c875b91439f)の Disable Secure boot や Disable nouveau は最近の環境で必要かどうか知らない?

3月ごろにセットアップした PC では、もう必要なかった。けど、その後 NVIDIA driver の更新で環境が壊れた。(GUI ログインできない。SSH はできる。)

それらの disable 作業が必要だったのかもしれないと疑っている。

**Comment by S-Kaisei** [comment]
>>> Disable Secure boot や Disable nouveau は最近の環境で必要かどうか知らない?
あんまり聞いたことない
>>> NVIDIA driver の更新で環境が壊れた
前のバージョンのドライバーとコンフリクトしたとか
前のドライバーを削除してから、インストールした？

**Comment by peaceiris** [comment]
Disable 系は設定項目もなくなった気がするから、書かないことにするわ。

> 前のバージョンのドライバーとコンフリクトしたとか
> 前のドライバーを削除してから、インストールした？

`sudo apt upgrade` にお任せしてるからわからん。俺の環境だけで、他に同じ症状の人が現れないのであれば気にしなくていいかな。

**Comment by S-Kaisei** [comment]
こっちでもいろいろ試してみて、できたら報告するわ。

**Comment by peaceiris** [comment]
とりあえずコンテンツは追加されたので close
