### ISSUE TITLE
gh-pages の index の setup について

### ISSUE THREAD

**Issue by S-Kaisei** [SI-Aizu/documentation#46]
@peaceiris 

"NVIDIA Driver の更新" を "NVIDIA Driver" として index に追加していいような気がする。
あと、docker をインストールする前に Driver を更新、インストールした方がいいと思うから

1. Ubuntu
2. NVIDIA Driver
3. Docker

でどうかな。

**Comment by peaceiris** [comment]
- NVIDIA Driver
  - NVIDIA Driver のインストール
  - NVIDIA Driver の更新

みたいな感じかな。いいね!

**Comment by peaceiris** [comment]
まだ対応していないのでreopenします
