### ISSUE TITLE
tutorial: Data Augmentation

### ISSUE THREAD

**Issue by S-Kaisei** [SI-Aizu/documentation#47]

**Comment by peaceiris** [comment]
## iris のメモ用コメント

**Comment by peaceiris** [comment]
> - [Module: tf.keras.datasets  |  TensorFlow Core v2.2.0](https://www.tensorflow.org/api_docs/python/tf/keras/datasets)

`tensorflow.keras.datasets` に

- cifar100
- cifar10
- fashion_mnist

とかあるからここらへんをターゲットにすればいいかも。

**Comment by S-Kaisei** [comment]
```
def flip(image):
    return tf.image.flip_left_right(image)

def grayscale(image):
    return tf.image.rgb_to_grayscale(image)

def saturate(image):
    return tf.image.adjust_saturation(image, 3)

def bright(image):
    return tf.image.adjust_brightness(image, 0.4)

def rotate(image):
    return tf.image.rot90(image,k=1)

def crop(image):
    return tf.image.central_crop(image, central_fraction=0.5)

l = [flip,grayscale,saturate, bright, rotate, crop]
for i in range(random.randrange(1,4)):
    image = random.choice(l)(image)

visualize(image,image,"dev.jpg")
```

拡張の方法をランダムに選ぶコード書いてみたんだけどどうかな。
1画像に対する処理の回数も1~3でランダムに for loop するようにもしてみた。

![dev](https://user-images.githubusercontent.com/39023477/86495868-fe377900-bdb5-11ea-8b2a-de3e0547a1ce.jpg)

**Comment by peaceiris** [comment]
お、いいね。

> ランダムに前処理を適用する

みたいな名前のセクションとして同じページに追加しようか。

あと、

### 「一つずつ」じゃなくて複数でもいいかなと思った

例えば `flip + crop` とか。

- いくつの処理を実行するか
- どの組み合わせを選ぶか

もランダムに。

### 閾値の幅もランダムに

例えば `bright` は 0.4 to 0.6 でランダムに、みたいなのをよく見るので。

**Comment by S-Kaisei** [comment]
> 一つずつ」じゃなくて複数でもいいかなと思った
```
for i in range(random.randrange(1,4)):
    image = random.choice(l)(image)
```
その処理がここに該当する。
今回は1~3回ランダムで同じ画像に対して実行している。

> 閾値の幅もランダムに      

tensorflow に random に閾値を変えれられる関数があるからそっちを実装する。

**Comment by S-Kaisei** [comment]
このランダムなデータ拡張を `cifar10` に対して実装していきます。

**Comment by peaceiris** [comment]
> > 一つずつ」じゃなくて複数でもいいかなと思った
> 
> ```
> for i in range(random.randrange(1,4)):
>     image = random.choice(l)(image)
> ```
> 
> その処理がここに該当する。
> 今回は1~3回ランダムで同じ画像に対して実行している。

なるほど把握。

> > 閾値の幅もランダムに
> 
> tensorflow に random に閾値を変えれられる関数があるからそっちを実装する。

了解 👍
