### ISSUE TITLE
tutorial: Git and GitHub

### ISSUE THREAD

**Issue by S-Kaisei** [SI-Aizu/documentation#70]

**Comment by peaceiris** [comment]
これをやってもらうのを行程に入れるといいかも。

- [Introduction to GitHub | GitHub Learning Lab](https://lab.github.com/githubtraining/introduction-to-github)
- [Bot と一緒にインタラクティブに GitHub を学べる GitHub Learning Lab は素晴らしい学習体験だった - kakakakakku blog](https://kakakakakku.hatenablog.com/entry/2020/06/23/095242)
