### ISSUE TITLE
画像置き場

### ISSUE THREAD

**Issue by S-Kaisei** [SI-Aizu/documentation#71]
https://app.diagrams.net/

**Comment by peaceiris** [comment]
もしくは、こんな感じでコメントに画像をアップロードすると以下のように URL が発行されるので、これを Markdown に貼り付けるでも良い。

```html
<img width="892" alt="Screen Shot 2020-06-11 at 11 29 58" src="https://user-images.githubusercontent.com/30958501/84338454-106b3080-abd7-11ea-91b4-6659e1a998dd.png">
```

<img width="892" alt="Screen Shot 2020-06-11 at 11 29 58" src="https://user-images.githubusercontent.com/30958501/84338454-106b3080-abd7-11ea-91b4-6659e1a998dd.png">

**Comment by S-Kaisei** [comment]
<details>
<summary>👉 Click to expand</summary>
![conv2D](https://user-images.githubusercontent.com/39023477/84355712-04df3000-abfe-11ea-83c1-13316f64af1c.jpg)
![Dense](https://user-images.githubusercontent.com/39023477/84370861-ceacab00-ac13-11ea-9113-ec1da955ca0e.jpg)
![Maxpooling](https://user-images.githubusercontent.com/39023477/84375763-01a66d00-ac1b-11ea-83f6-6188acb911fb.jpg)
</details>

**Comment by peaceiris** [comment]
<details>
<summary>👉 Click to expand</summary>

![export_settings](https://user-images.githubusercontent.com/30958501/85507840-f8ab9780-b62d-11ea-8b81-b80df8634890.jpg)
![progress](https://user-images.githubusercontent.com/30958501/85507845-fa755b00-b62d-11ea-96fe-8e50b9263eb1.jpg)
![project](https://user-images.githubusercontent.com/30958501/85507855-fc3f1e80-b62d-11ea-84af-82b2b424f6d2.jpg)
![source_connection](https://user-images.githubusercontent.com/30958501/85507859-fcd7b500-b62d-11ea-93d0-b5ed82414bad.jpg)
![tags_editor_export](https://user-images.githubusercontent.com/30958501/85507863-fd704b80-b62d-11ea-98b8-b44139164ff0.jpg)
![tags_editor](https://user-images.githubusercontent.com/30958501/85507869-fe08e200-b62d-11ea-9a5e-3da01459eec6.jpg)


</details>
