### ISSUE TITLE
gh-pages の index の統一

### ISSUE THREAD

**Issue by S-Kaisei** [SI-Aizu/documentation#77]
gh-pages の index の 作り方に統一性を持たせたい。
英語と日本語が混同してたり、tutorial で getting start があったりなかったりしているため。

**Comment by peaceiris** [comment]
> 英語と日本語が混同

これは特に意識してなかった。どっちもある方が検索に引っかかりやすいかなとは思ってる。

> tutorial で getting start があったりなかったりしている

GitHub tutorial に getting started が必要だね。

**Comment by S-Kaisei** [comment]
<img width="243" alt="スクリーンショット 2020-06-11 12 49 55" src="https://user-images.githubusercontent.com/39023477/84343040-0ef33580-abe2-11ea-9211-c04dfd7768e3.png">
transfer learning の後に転移学習けど、こういう書き方で統一ってこと？          

GitHub tutorial には index があるけど他のタイトルにも index をつける？
setup の環境構築も index になる？

**Comment by peaceiris** [comment]
> transfer learning の後に転移学習ってなってるけど、こういう書き方で統一？

これは例外。Dockerfile とかもディレクトリで管理したいとなると MkDocs の仕様上こうするしかない。他にいいタイトルがあれば代えたい。

> GitHub tutorial には index があるけど他のタイトルにも index をつける？

Yes. サイドバーは自動生成なので、もっとわかりやすい目次用のページ (index) を作った方がいいかも。

> setup の環境構築も index になる？

yes.
